version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    container_name: costos
    environment:
      PORT: 3001
      MONGO_URL: mongodb://mongo:27017
      DB_NAME: costos
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./mongod.conf:/etc/mongod.conf
